application: fanfou-timer
version: 2
runtime: python
api_version: 1

handlers:
- url: /
  static_files: mainpage.html
  upload: mainpage.html
  login: required

- url: /timer
  script: timer.py

- url: /fix
  script: fix.py
  login: admin

- url: /static
  static_dir: static
  expiration: 7d

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: favicon.ico
  expiration: 7d

- url: /.*
  script: main.py
  login: required
